import * as fs from 'node:fs';
import * as path from 'node:path';
import { type ResolvedSource, type TargetConfig } from '../types.js';
import { type TargetFormatter, resolveTargetPath } from './base.js';
import { ensureParentDir } from '../utils/fs.js';
import { logger } from '../utils/logger.js';

/**
 * GitHub Copilot target formatter.
 *
 * Merges all skills and rules into a single file:
 *   .github/copilot-instructions.md
 */
export class CopilotFormatter implements TargetFormatter {
  readonly name = 'Copilot';

  sync(projectRoot: string, source: ResolvedSource, config: TargetConfig): string[] {
    const written: string[] = [];
    const targetPath = config.skills_path ?? '.github/copilot-instructions.md';
    const mode = config.mode ?? 'merge';

    if (mode === 'merge') {
      return this.syncMerged(projectRoot, source, targetPath, written);
    }

    // Copy mode — individual files (less common for Copilot)
    return this.syncCopied(projectRoot, source, targetPath, written);
  }

  private syncMerged(
    projectRoot: string,
    source: ResolvedSource,
    targetPath: string,
    written: string[]
  ): string[] {
    const sections: string[] = [];

    // Header
    sections.push(
      `<!-- Auto-generated by playbook-sync from "${source.config.name}" -->`,
      `<!-- Do not edit manually — changes will be overwritten on next sync -->`,
      ''
    );

    // AGENTS.md content
    if (source.content.agents_md) {
      const content = fs.readFileSync(source.content.agents_md, 'utf-8');
      sections.push(content, '\n---\n');
    }

    // CLAUDE.md content
    if (source.content.claude_md) {
      const content = fs.readFileSync(source.content.claude_md, 'utf-8');
      sections.push(`## CLAUDE.md\n`);
      sections.push(content);
      sections.push('\n---\n');
    }

    // README.md content
    if (source.content.readme) {
      const content = fs.readFileSync(source.content.readme, 'utf-8');
      sections.push(`## README\n`);
      sections.push(content);
      sections.push('\n---\n');
    }

    // Agents directory
    for (const agentPath of source.content.agents_dir) {
      const srcPath = path.join(source.local_path, agentPath);
      const content = fs.readFileSync(srcPath, 'utf-8');
      const agentName = path.basename(agentPath, path.extname(agentPath));
      sections.push(`## Agent: ${agentName}\n`);
      sections.push(content);
      sections.push('\n---\n');
    }

    // Skills
    for (const skill of source.content.skills) {
      const content = fs.readFileSync(skill.skill_md_path, 'utf-8');
      sections.push(`## Skill: ${skill.name}\n`);
      sections.push(content);
      sections.push('\n---\n');
    }

    // Rules
    for (const rulePath of source.content.rules) {
      const srcPath = path.join(source.local_path, rulePath);
      const content = fs.readFileSync(srcPath, 'utf-8');
      const ruleName = path.basename(rulePath, path.extname(rulePath));
      sections.push(`## Rule: ${ruleName}\n`);
      sections.push(content);
      sections.push('\n---\n');
    }

    // Docs
    for (const docPath of source.content.other_docs) {
      const srcPath = path.join(source.local_path, docPath);
      const content = fs.readFileSync(srcPath, 'utf-8');
      const docName = path.basename(docPath, path.extname(docPath));
      sections.push(`## Doc: ${docName}\n`);
      sections.push(content);
      sections.push('\n---\n');
    }

    const dstPath = resolveTargetPath(projectRoot, targetPath);
    ensureParentDir(dstPath);
    fs.writeFileSync(dstPath, sections.join('\n'), 'utf-8');

    written.push(targetPath);
    logger.success(`  ${this.name}: merged → ${targetPath}`);
    return written;
  }

  private syncCopied(
    projectRoot: string,
    source: ResolvedSource,
    _targetPath: string,
    written: string[]
  ): string[] {
    // For copy mode, use a directory
    const dir = '.github/copilot-skills';
    for (const skill of source.content.skills) {
      const content = fs.readFileSync(skill.skill_md_path, 'utf-8');
      const dstPath = resolveTargetPath(
        projectRoot,
        path.join(dir, `${skill.name}.md`)
      );
      ensureParentDir(dstPath);
      fs.writeFileSync(dstPath, content, 'utf-8');
      written.push(path.join(dir, `${skill.name}.md`).replace(/\\/g, '/'));
    }

    logger.success(`  ${this.name}: ${written.length} files → ${dir}`);
    return written;
  }
}
